projects:
  amplifyDatasource:
    schemaPath: graphql/schema.json
    includes:
      - graphql/**/*.graphql
    excludes:
      - ./amplify/**
    extensions:
      amplify:
        codeGenTarget: swift
        generatedFileName: AppleSDKResearchAmplifyAPI.swift
        docsFilePath: graphql
